# Made by Skyler Blue Spillers - Innovative Information Technology Resolutions LLC
version: '3.8'
services:
  shadowchat:
    build: .
    deploy:
      replicas: 200
      resources:
        limits:
          cpus: '20.0'
          memory: 64G
  p2p-cluster-v7:
    build: .
    command: python p2p/node_p2p.py
    deploy:
      replicas: 120