# Made by Skyler Blue Spillers - Innovative Information Technology Resolutions LLC
version: '3.8'
services:
  shadowchat:
    build: .
    deploy:
      replicas: 500
      resources:
        limits:
          cpus: '32.0'
          memory: 128G
  p2p-cluster-v10:
    build: .
    command: python p2p/node_p2p.py
    deploy:
      replicas: 250