# Made by Skyler Blue Spillers - Innovative Information Technology Resolutions LLC
version: '3.8'
services:
  shadowchat:
    build: .
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
  p2p:
    build: .
    command: python p2p/node_p2p.py
    deploy:
      replicas: 8