# Made by Skyler Blue Spillers - Innovative Information Technology Resolutions LLC
version: '3.8'
services:
  shadowchat:
    build: .
    deploy:
      replicas: 20
      resources:
        limits:
          cpus: '4.0'
          memory: 8G
  p2p-cluster:
    build: .
    command: python p2p/node_p2p.py
    deploy:
      replicas: 15