# Made by Skyler Blue Spillers - Innovative Information Technology Resolutions LLC
version: '3.8'
services:
  shadowchat:
    build: .
    deploy:
      replicas: 30
      resources:
        limits:
          cpus: '6.0'
          memory: 12G
  p2p-cluster-v2:
    build: .
    command: python p2p/node_p2p.py
    deploy:
      replicas: 20