# Made by Skyler Blue Spillers - Innovative Information Technology Resolutions LLC
version: '3.8'
services:
  shadowchat:
    build: .
    deploy:
      replicas: 50
      resources:
        limits:
          cpus: '8.0'
          memory: 16G
  p2p-cluster-v3:
    build: .
    command: python p2p/node_p2p.py
    deploy:
      replicas: 30